version: '3'
services:
  webapp:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
  db:
    build: sql/
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - . :/var/lib/mysql
